layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: Azure
    web_url: https://azure.microsoft.com/en-us/
    image_url: https://i1.wp.com/buildazure.com/wp-content/uploads/2017/09/Azure.png?resize=519%2C387&ssl=1 

  - name: Docker
    web_url: https://www.docker.com/
    image_url: https://www.docker.com/sites/default/files/social/docker_facebook_share.png    

  - name: InfluxDB
    web_url: https://www.influxdata.com/
    image_url: https://d33wubrfki0l68.cloudfront.net/e40701d9c1ee6ad1757efad404f56b8083fec49f/e6260/images/influx_logo.png

  - name: Grafana
    web_url: https://grafana.com/
    image_url: https://freeicons.io/laravel/public/uploads/icons/png/8135670941548141941-256.png

